$kind: http-request
name: Update Task
method: PUT
url: "{{baseUrl}}/api/task/019dd7c2-23b9-7035-854e-60565e038c1b"
order: 5000
headers:
  Content-Type: application/json
body:
  type: json
  content: |-
    {
        "categoryId": null,
        "title": "di choi",
        "description": "Di Vinh Long",
        "dueDate": "2026-04-25T00:00:00Z",
        "isCompleted": false,
        "status": "Pending",
        "visibility": "Public"
    }
