$kind: http-request
name: Update Task
method: PUT
url: "{{baseUrl}}/api/task/10"
order: 5000
headers:
  Content-Type: application/json
body:
  type: json
  content: |-
    {
            "categoryId": null,
            "title": "lam bai",
            "description": "Task description here",
            "dueDate": "2026-04-24T19:00:00Z",
            "isCompleted": false,
            "status": "Pending",
            "visibility": "Public"
        }
